version: "3.8"

services:
  postgres-service:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=post_service
      - TZ=Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/create_tabel.sql

  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - postgres-service
    restart: on-failure