// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	User     string  `json:"user"`
	Text     string  `json:"text"`
}

type NewPost struct {
	User            string `json:"user"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsEnabled *bool  `json:"commentsEnabled,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
