logger:
  level: "local"
server:
  address: ":8081"
  timeout: 4s
  iddletimeout: 40s
  shutdowntimeout: 10s
  complexitylimit: 1000
db:
  host: "postgres_db"
  port: 5432
  username: "postgres"
  name: "post_service"
  password: "postgres"